Adds a view mode
illuminatedspace/automagically pull request #83
Opened 2017-03-26 19:06 UTC by illuminatedspace

closes #73

2017-03-26 22:09 UTC, clairefreehafer commented on app/components/Canvas.js
> +    // this.renderCustomDragLayer = this.renderCustomDragLayer.bind(this)
comment

2017-03-26 22:11 UTC, clairefreehafer commented on app/components/Page.js
> +  // render() {
comment

2017-03-26 22:11 UTC, clairefreehafer requested changes
couple comments

2017-03-27 14:40 UTC, ariamoraine approved these changes

2017-03-27 14:42 UTC, merged